package com.steve.aecdiag;
import android.Manifest;import android.util.Log;import android.app.Activity;import android.os.*;import android.media.*;import android.media.audiofx.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.widget.*;import java.util.*;
public class MainActivity extends Activity{static final String TAG="AecDiag";AudioRecord r;AcousticEchoCanceler a;TextView s;int e;long t;volatile boolean read;Thread th;long n;double ss;int pk;
public void onCreate(Bundle b){super.onCreate(b);t=SystemClock.elapsedRealtimeNanos();if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},1);LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);s=new TextView(this);s.setTextColor(Color.BLACK);x.addView(s,new LinearLayout.LayoutParams(-1,0,1));String[] q={"Query Effects","Create AudioRecord","Create AEC","Enable AEC","Start Recording","Stop Recording","Disable AEC","Release AEC","Release AudioRecord","Capture Snapshot"};for(String z:q){Button b1=new Button(this);b1.setText(z);b1.setOnClickListener(v->step(z));x.addView(b1,new LinearLayout.LayoutParams(-1,0,1));}setContentView(x);u();}
void l(String z){e++;Log.i(TAG,"event="+String.format(Locale.US,"%03d",e)+" t_ms="+((SystemClock.elapsedRealtimeNanos()-t)/1000000)+" "+z);}
void step(String z){try{if(z.equals("Query Effects")){l("STEP=query_effects aec_available="+AcousticEchoCanceler.isAvailable()+" ns_available="+NoiseSuppressor.isAvailable()+" agc_available="+AutomaticGainControl.isAvailable());for(AudioEffect.Descriptor d:AudioEffect.queryEffects())l("descriptor name="+d.name+" implementor="+d.implementor+" type="+d.type+" implementation="+d.uuid);}else if(z.equals("Create AudioRecord")){if(r!=null)return;int m=AudioRecord.getMinBufferSize(16000,16,2);r=new AudioRecord(6,16000,16,2,Math.max(m*2,6400));l("STEP=create_record state="+r.getState()+" session="+r.getAudioSessionId()+" rate="+r.getSampleRate()+" channels="+r.getChannelCount()+" format="+r.getAudioFormat()+" buffer="+Math.max(m*2,6400));}else if(z.equals("Create AEC")){if(r==null||a!=null)return;a=AcousticEchoCanceler.create(r.getAudioSessionId());l("STEP=create_aec null="+(a==null)+(a==null?"":" enabled="+a.getEnabled()+" control="+a.hasControl()+" type="+a.getDescriptor().type+" implementation="+a.getDescriptor().uuid));}else if(z.equals("Enable AEC")){if(a==null)return;boolean b=a.getEnabled();int st=a.setEnabled(true);l("STEP=enable_aec status="+st+" before="+b+" after="+a.getEnabled()+" control="+a.hasControl());}else if(z.equals("Start Recording")){if(r==null)return;r.startRecording();read=true;th=new Thread(()->loop());th.start();l("STEP=start_recording state="+r.getRecordingState());}else if(z.equals("Stop Recording")){read=false;if(r!=null)try{r.stop();}catch(Exception q1){}l("STEP=stop_recording");}else if(z.equals("Disable AEC")){if(a!=null){boolean b=a.getEnabled();int st=a.setEnabled(false);l("STEP=disable_aec status="+st+" before="+b+" after="+a.getEnabled());}}else if(z.equals("Release AEC")){if(a!=null){a.release();a=null;l("STEP=release_aec");}}else if(z.equals("Release AudioRecord")){read=false;if(r!=null){try{r.stop();}catch(Exception q1){}r.release();r=null;l("STEP=release_record");}}else if(z.equals("Capture Snapshot")){l("SNAPSHOT record="+(r==null?"null":r.getState()+"/"+r.getRecordingState()+" session="+r.getAudioSessionId())+" aec="+(a==null?"null":a.getEnabled()+"/"+a.hasControl()));}}catch(Exception q1){l("STEP="+z.replace(' ','_')+" ERROR="+q1);}u();}
void loop(){short[] b=new short[320];while(read&&r!=null){int k=r.read(b,0,b.length);if(k>0){for(int i=0;i<k;i++){ss+=(double)b[i]*b[i];pk=Math.max(pk,Math.abs((int)b[i]));n++;}if(n>=16000){l("PCM samples="+n+" rms="+Math.sqrt(ss/n)+" peak="+pk);n=0;ss=0;pk=0;}}}}
void u(){s.setText("AudioRecord="+(r==null?"null":r.getState()+"/"+r.getRecordingState())+" session="+(r==null?"-":r.getAudioSessionId())+"\nAEC="+(a==null?"null":"enabled="+a.getEnabled()+" control="+a.hasControl())+"\nEvents="+e);}
protected void onDestroy(){read=false;if(a!=null)a.release();if(r!=null)r.release();super.onDestroy();}}
